services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: harmonii-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${MSSQL_SA_PASSWORD}' -Q 'SELECT 1' -C"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "1433:1433"
    networks:
      - harmonii-network

  api:
    build:
      context: .
      dockerfile: harmonii.Server/Dockerfile
    container_name: harmonii-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=HarmoniiDb;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;
      - JWT__ValidAudience=${JWT_VALID_AUDIENCE}
      - JWT__ValidIssuer=${JWT_VALID_ISSUER}
      - JWT__Token=${JWT_TOKEN}
      - Minio__Endpoint=minio:9000
      - Minio__AccessKey=${MINIO_ROOT_USER}
      - Minio__SecretKey=${MINIO_ROOT_PASSWORD}
      - Minio__BucketName=harmonii-bucket
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - harmonii-network

  minio:
    image: minio/minio
    container_name: harmonii-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_API_CORS_ALLOW_ORIGIN: "*"
      MINIO_SERVER_URL: "http://localhost:9000"
      MINIO_BROWSER_REDIRECT_URL: "http://localhost:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - harmonii-network

  adminer:
    image: adminer
    container_name: harmonii-adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - harmonii-network

  frontend:
    build:
      context: ./harmonii.client # Frontend proje klasörün
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8080/api
    container_name: harmonii-frontend
    ports:
      - "3000:80" # Tarayıcıdan localhost:3000 ile erişeceksin
    environment:
      - NODE_ENV=production
    depends_on:
      - api
    networks:
      - harmonii-network

volumes:
  mssql-data:
  minio-data:

networks:
  harmonii-network:
    driver: bridge
